// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"loadbalancing-controller/pkg/apis/keti/v1alpha1.OpenMCPLoadbalancing":       schema_pkg_apis_keti_v1alpha1_OpenMCPLoadbalancing(ref),
		"loadbalancing-controller/pkg/apis/keti/v1alpha1.OpenMCPLoadbalancingSpec":   schema_pkg_apis_keti_v1alpha1_OpenMCPLoadbalancingSpec(ref),
		"loadbalancing-controller/pkg/apis/keti/v1alpha1.OpenMCPLoadbalancingStatus": schema_pkg_apis_keti_v1alpha1_OpenMCPLoadbalancingStatus(ref),
	}
}

func schema_pkg_apis_keti_v1alpha1_OpenMCPLoadbalancing(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OpenMCPLoadbalancing is the Schema for the openmcploadbalancings API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							//Ref: ref("multicluster-controller/controller/loadbalancing-controller/pkg/apis/keti/v1alpha1.OpenMCPLoadbalancingSpec"),
							Ref: ref("loadbalancing-controller/pkg/apis/keti/v1alpha1.OpenMCPLoadbalancingSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("loadbalancing-controller/pkg/apis/keti/v1alpha1.OpenMCPLoadbalancingStatus"),
							//Ref: ref("multicluster-controller/controller/loadbalancing-controller/pkg/apis/keti/v1alpha1.OpenMCPLoadbalancingStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			//"k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta", "multicluster-controller/controller/loadbalancing-controller/pkg/apis/keti/v1alpha1.OpenMCPLoadbalancingSpec", "multicluster-controller/controller/loadbalancing-controller/pkg/apis/keti/v1alpha1.OpenMCPLoadbalancingStatus"},

			"k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta", "loadbalancing-controller/pkg/apis/keti/v1alpha1.OpenMCPLoadbalancingSpec", "loadbalancing-controller/pkg/apis/keti/v1alpha1.OpenMCPLoadbalancingStatus"},
	}
}

func schema_pkg_apis_keti_v1alpha1_OpenMCPLoadbalancingSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OpenMCPLoadbalancingSpec defines the desired state of OpenMCPLoadbalancing",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_keti_v1alpha1_OpenMCPLoadbalancingStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OpenMCPLoadbalancingStatus defines the observed state of OpenMCPLoadbalancing",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
