apiVersion: keti.example.com/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: log-level
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: All-OpenMCP-Resource-Controller
      policies:
        - type: Level
          value:
            - "2"
  policyStatus: Enabled
