apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPHybridAutoScaler
metadata:
  name: test-has
  namespace: test
spec:
  mainController: OpenMCP
  scalingOptions:
    cpaTemplate:
      scaleTargetRef:
        kind: OpenMCPDeployment
        name: test-has-pod
      minReplicas: 4
      maxReplicas: 5
