apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  clusters:
#    - cluster01
    - cluster02
#    - cluster03
  labels:
    app: wordpress
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - image: wordpress
              name: wordpress
              env:
              - name: WORDPRESS_DB_HOST
                value: mysql:3306
              - name: WORDPRESS_DB_NAME
                value: keti
              - name: WORDPRESS_DB_USER
                value: keti
              - name: WORDPRESS_DB_PASSWORD
                value: ketilinux
              ports:
                - containerPort: 8080
                  name: wordpress
              volumeMounts:
                - name: wordpress-persistent-storage
                  mountPath: /var/www/html
              resources:
                requests:
                  memory: 1Gi
                  cpu: 100m
#            - name: php-apache
#              image: k8s.gcr.io/hpa-example
#              ports:
#                - containerPort: 80
#              resources:
#                requests:
#                  memory: 500Mi
#                  cpu: 250m
          volumes:
            - name: wordpress-persistent-storage
              persistentVolumeClaim:
                claimName: wordpress-volumeclaim

