apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPersistentVolume
metadata:
  name: pv002
  labels:
    type: local
spec:
  clusters:
    - cluster02
  labels:
    type: local
  template:
    spec:
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteOnce
      nfs:
        path: /home/nfs/wordpress/data001/pv002
        server: "10.0.3.20"
        readOnly: false