apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  template:
    spec:
      type: LoadBalancer
      ports:
#        - name: port-1
#          port: 80
#          protocol: TCP
#          targetPort: 80
        - name: http-wordpress
          port: 80
          protocol: TCP
          targetPort: 80
#          nodePort: 31188
      selector:
        app: wordpress
