apiVersion: v1
kind: ConfigMap
metadata:
 namespace: metallb-system
 name: config
data:
 config: |
   address-pools:
   - name: default
     protocol: layer2
     addresses:
     #- 115.94.141.62
     - 10.0.3.191-10.0.3.200
     #- 192.168.1.240-192.168.1.250
