apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: iot-gateway-svc
  namespace: openmcp
spec:
  template:
    spec:
      type: LoadBalancer
      ports:
      - port: 8888
        name: http
      - port: 5683
        name: coap
      - port: 1883
        name: mqtt
      - port: 80
        targetPort: 7070
        name: sysbench
      selector:
        component: iot-gateway-svc
