// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRegistry) DeepCopyInto(out *GlobalRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRegistry.
func (in *GlobalRegistry) DeepCopy() *GlobalRegistry {
	if in == nil {
		return nil
	}
	out := new(GlobalRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRegistryList) DeepCopyInto(out *GlobalRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRegistryList.
func (in *GlobalRegistryList) DeepCopy() *GlobalRegistryList {
	if in == nil {
		return nil
	}
	out := new(GlobalRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRegistrySpec) DeepCopyInto(out *GlobalRegistrySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRegistrySpec.
func (in *GlobalRegistrySpec) DeepCopy() *GlobalRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(GlobalRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRegistryStatus) DeepCopyInto(out *GlobalRegistryStatus) {
	*out = *in
	in.LastSuccessDate.DeepCopyInto(&out.LastSuccessDate)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRegistryStatus.
func (in *GlobalRegistryStatus) DeepCopy() *GlobalRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(GlobalRegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageList) DeepCopyInto(out *ImageList) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageList.
func (in *ImageList) DeepCopy() *ImageList {
	if in == nil {
		return nil
	}
	out := new(ImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRegistry) DeepCopyInto(out *NodeRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRegistry.
func (in *NodeRegistry) DeepCopy() *NodeRegistry {
	if in == nil {
		return nil
	}
	out := new(NodeRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRegistryList) DeepCopyInto(out *NodeRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRegistryList.
func (in *NodeRegistryList) DeepCopy() *NodeRegistryList {
	if in == nil {
		return nil
	}
	out := new(NodeRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRegistrySpec) DeepCopyInto(out *NodeRegistrySpec) {
	*out = *in
	if in.ImageLists != nil {
		in, out := &in.ImageLists, &out.ImageLists
		*out = make([]ImageList, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRegistrySpec.
func (in *NodeRegistrySpec) DeepCopy() *NodeRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(NodeRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRegistryStatus) DeepCopyInto(out *NodeRegistryStatus) {
	*out = *in
	in.LastSuccessDate.DeepCopyInto(&out.LastSuccessDate)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRegistryStatus.
func (in *NodeRegistryStatus) DeepCopy() *NodeRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(NodeRegistryStatus)
	in.DeepCopyInto(out)
	return out
}
