apiVersion: openmcp.k8s.io/v1alpha1
kind: Migration
metadata:
  name: migrations3
spec:
  migrationServiceSource:
  - sourceCluster: cluster1
    targetCluster: cluster2
    nameSpace: openmcp
    serviceName: openmcp-deploy
    migrationSource:
    - resourceName: openmcp-deployment
      resourceType: Deployment
