apiVersion: openmcp.k8s.io/v1alpha1
kind: Migration
metadata:
  name: iot-gateway-migration
spec:
  MigrationServiceSource:
  - SourceCluster: cluster1
    TargetCluster: cluster2
    NameSpace: default
    ServiceName: iot-gateway
    MigrationSource:
    - ResourceName: iot-gateway
      ResourceType: Deployment
    - ResourceName: iot-gateway-sv
      ResourceType: Service
    - ResourceName: iot-gateway-pv
      ResourceType: PersistentVolume
    - ResourceName: iot-gateway-pvc
      ResourceType: PersistentVolumeClaim
