apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: test-deploy
  namespace: test
spec:
  replicas: 30
  clusters:
    - cluster01
    - cluster02
    - cluster03
#    - cluster05
  labels:
    app: test-pod
    affinity: "yes"
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - name: php-apache
              image: k8s.gcr.io/hpa-example
              #imagePullPolicy: IfNotPresent
