apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: test-deploy-eks
  namespace: test
spec:
  replicas: 30
  clusters:
    - cluster12
    - cluster13
    - cluster14
  labels:
    app: test-pod-eks
    affinity: "yes"
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - name: php-apache
              image: k8s.gcr.io/hpa-example
              #imagePullPolicy: Always
              #resources:
              #requests:
              #  memory: 10Mi
              #  cpu: 100m
