apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: test-deploy-aks
  namespace: test
spec:
  replicas: 30
  clusters:
    - cluster15
    - cluster16
    - cluster17
  labels:
    app: test-pod-aks
    affinity: "yes"
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - name: nginx
              image: nginx
              #imagePullPolicy: Always
