apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: openmcp
spec:
  replicas: 2
  selector:
    matchLabels:
      name: test-deploy
  template:
     metadata:
      labels:
        name: test-deploy
     spec:
       imagePullSecrets:
         - name: regcred
       containers:
         - image: nginx
           name: nginx
           resources:
             requests:
               memory: "10"
               cpu: "0.1"
