apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: postgis
  namespace: smartcity
  #namespace: default
  labels:
    app: postgis
spec:
  template:
    spec:
      ports:
        - name: "5432"
          port: 5432
          targetPort: 5432
      selector:
        app: postgis
