apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPersistentVolume
metadata:
  name: post-pv-claim0
spec:
  template:
    spec:
      capacity:
        storage: 2Gi
      storageClassName: post
      accessModes:
      - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      nfs:
        path: /k8s_smartcity/openmcp/sql
        server: "115.94.141.62"
        readOnly: false
