apiVersion: v1
kind: Service
metadata:
  name: cluster-metric-collector
  namespace: openmcp
  labels:
    name: cluster-metric-collector
spec:
  type: LoadBalancer
  ports:
  - port: 2052
    targetPort: 2052
    nodePort: 32052
    protocol: TCP
  selector:
    name: cluster-metric-collector
