apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: data-manager
  namespace: smartcity
  labels:
    app: data-manager
spec:
  template:
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        app: data-manager
