apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: data-service-broker
  namespace: smartcity
  labels:
    app: data-service-broker
spec:
  template:
    spec:
      ports:
        - name: "8082"
          port: 8082
          targetPort: 8082
      selector:
        app: data-service-broker
