apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: openmcp-service
  namespace: openmcp
spec:
  template:
    spec:
      type: LoadBalancer
      ports:
      - name: http
        port: 80
      selector:
        app: openmcp-nginx
