apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPHybridAutoScaler
metadata:
  name: has-iot-gateway
  namespace: openmcp
spec:
  mainController: OpenMCP
  scalingOptions:
    cpaTemplate:
      scaleTargetRef:
        kind: OpenMCPDeployment
        name: iot-gateway
      minReplicas: 1
      maxReplicas: 4
