apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: post-scheduling-type
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: OpenMCPSchduler
      policies:
        - type: priority
          value:
            - FIFO
  rangeOfApplication: All
  policyStatus: Enabled
