apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-api-server-cert
  labels:
    app: apiserver
spec:
  capacity:
    storage: 2Gi
  storageClassName: apiserver
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/nfs/pv/api-server/cert
    server: "10.0.3.20"
    readOnly: false

