apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPVirtualService
metadata:
  name: bookinfo
#  namespace: bookinfo
spec:
  hosts:
  #- "*"
  - "keti.productpage.openmcp.in"
  gateways:
  - istio-ingress-gateway
  http:
  - match:
    - uri:
       exact: /productpage
    - uri:
       prefix: /static
    - uri:
       exact: /login
    - uri:
       exact: /logout
    - uri:
       prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
