apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPIngress
metadata:
  name: kiali-ingress
  namespace: istio-system
spec:
  template:
    spec:
      rules:
      - host: kiali.openmcp.com
        http:
          paths:
          - backend:
              serviceName: kiali
              servicePort: 20001
