apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeployment
  namespace: openmcp
spec:
  replicas: 4
  clusters:
  - "cluster1"
  - "cluster2"
  labels:
      app: openmcp-nginx
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
            resources:
              requests:
                memory: "10Mi"
                cpu: "0.1"
