apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: openmcp
# annotations:
#    metallb.universe.tf/allow-shared-ip: openmcp
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
    nodePort: 30003
  selector:
    app: influxdb
  type: NodePort

