// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: generated.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HASInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HPAName             string           `protobuf:"bytes,1,opt,name=HPAName,proto3" json:"HPAName,omitempty"`
	HPANamespace        string           `protobuf:"bytes,2,opt,name=HPANamespace,proto3" json:"HPANamespace,omitempty"`
	ClusterName         string           `protobuf:"bytes,3,opt,name=ClusterName,proto3" json:"ClusterName,omitempty"`
	HASRebalancingCount map[string]int32 `protobuf:"bytes,4,rep,name=HASRebalancingCount,proto3" json:"HASRebalancingCount,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	HPAMinORMaxReplicas map[string]int32 `protobuf:"bytes,5,rep,name=HPAMinORMaxReplicas,proto3" json:"HPAMinORMaxReplicas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	HPACurrentReplicas  map[string]int32 `protobuf:"bytes,6,rep,name=HPACurrentReplicas,proto3" json:"HPACurrentReplicas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *HASInfo) Reset() {
	*x = HASInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HASInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HASInfo) ProtoMessage() {}

func (x *HASInfo) ProtoReflect() protoreflect.Message {
	mi := &file_generated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HASInfo.ProtoReflect.Descriptor instead.
func (*HASInfo) Descriptor() ([]byte, []int) {
	return file_generated_proto_rawDescGZIP(), []int{0}
}

func (x *HASInfo) GetHPAName() string {
	if x != nil {
		return x.HPAName
	}
	return ""
}

func (x *HASInfo) GetHPANamespace() string {
	if x != nil {
		return x.HPANamespace
	}
	return ""
}

func (x *HASInfo) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *HASInfo) GetHASRebalancingCount() map[string]int32 {
	if x != nil {
		return x.HASRebalancingCount
	}
	return nil
}

func (x *HASInfo) GetHPAMinORMaxReplicas() map[string]int32 {
	if x != nil {
		return x.HPAMinORMaxReplicas
	}
	return nil
}

func (x *HASInfo) GetHPACurrentReplicas() map[string]int32 {
	if x != nil {
		return x.HPACurrentReplicas
	}
	return nil
}

type ResponseHAS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetCluster string `protobuf:"bytes,1,opt,name=TargetCluster,proto3" json:"TargetCluster,omitempty"`
}

func (x *ResponseHAS) Reset() {
	*x = ResponseHAS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generated_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseHAS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHAS) ProtoMessage() {}

func (x *ResponseHAS) ProtoReflect() protoreflect.Message {
	mi := &file_generated_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHAS.ProtoReflect.Descriptor instead.
func (*ResponseHAS) Descriptor() ([]byte, []int) {
	return file_generated_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseHAS) GetTargetCluster() string {
	if x != nil {
		return x.TargetCluster
	}
	return ""
}

type LBInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterNameList []string `protobuf:"bytes,1,rep,name=ClusterNameList,proto3" json:"ClusterNameList,omitempty"`
	ClientIP        string   `protobuf:"bytes,2,opt,name=ClientIP,proto3" json:"ClientIP,omitempty"`
}

func (x *LBInfo) Reset() {
	*x = LBInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generated_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LBInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBInfo) ProtoMessage() {}

func (x *LBInfo) ProtoReflect() protoreflect.Message {
	mi := &file_generated_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBInfo.ProtoReflect.Descriptor instead.
func (*LBInfo) Descriptor() ([]byte, []int) {
	return file_generated_proto_rawDescGZIP(), []int{2}
}

func (x *LBInfo) GetClusterNameList() []string {
	if x != nil {
		return x.ClusterNameList
	}
	return nil
}

func (x *LBInfo) GetClientIP() string {
	if x != nil {
		return x.ClientIP
	}
	return ""
}

type ResponseLB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScoreMap map[string]float64 `protobuf:"bytes,1,rep,name=ScoreMap,proto3" json:"ScoreMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
}

func (x *ResponseLB) Reset() {
	*x = ResponseLB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generated_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseLB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseLB) ProtoMessage() {}

func (x *ResponseLB) ProtoReflect() protoreflect.Message {
	mi := &file_generated_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseLB.ProtoReflect.Descriptor instead.
func (*ResponseLB) Descriptor() ([]byte, []int) {
	return file_generated_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseLB) GetScoreMap() map[string]float64 {
	if x != nil {
		return x.ScoreMap
	}
	return nil
}

type SchedInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName string `protobuf:"bytes,1,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
}

func (x *SchedInfo) Reset() {
	*x = SchedInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generated_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedInfo) ProtoMessage() {}

func (x *SchedInfo) ProtoReflect() protoreflect.Message {
	mi := &file_generated_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedInfo.ProtoReflect.Descriptor instead.
func (*SchedInfo) Descriptor() ([]byte, []int) {
	return file_generated_proto_rawDescGZIP(), []int{4}
}

func (x *SchedInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type ResponseSched struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RX string `protobuf:"bytes,1,opt,name=RX,proto3" json:"RX,omitempty"`
	TX string `protobuf:"bytes,2,opt,name=TX,proto3" json:"TX,omitempty"`
}

func (x *ResponseSched) Reset() {
	*x = ResponseSched{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generated_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseSched) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSched) ProtoMessage() {}

func (x *ResponseSched) ProtoReflect() protoreflect.Message {
	mi := &file_generated_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSched.ProtoReflect.Descriptor instead.
func (*ResponseSched) Descriptor() ([]byte, []int) {
	return file_generated_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseSched) GetRX() string {
	if x != nil {
		return x.RX
	}
	return ""
}

func (x *ResponseSched) GetTX() string {
	if x != nil {
		return x.TX
	}
	return ""
}

var File_generated_proto protoreflect.FileDescriptor

var file_generated_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x69, 0x0a, 0x07, 0x48,
	0x41, 0x53, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x50, 0x41, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x50, 0x41, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x48, 0x50, 0x41, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x48, 0x50, 0x41, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x41, 0x53, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x4e, 0x0a, 0x06, 0x4c,
	0x42, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x50, 0x22, 0x89, 0x01, 0x0a, 0x0a,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x42, 0x12, 0x3e, 0x0a, 0x08, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x4d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4c, 0x42, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x61, 0x70, 0x1a, 0x3b, 0x0a, 0x0d, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x27, 0x0a, 0x09, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x2f, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x52, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x52,
	0x58, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x58, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54,
	0x58, 0x32, 0x96, 0x02, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x6e, 0x61,
	0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x40, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x41, 0x53,
	0x4d, 0x69, 0x6e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x48, 0x41, 0x53, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x41, 0x53, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x48,
	0x41, 0x53, 0x4d, 0x61, 0x78, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x48, 0x41, 0x53, 0x49, 0x6e, 0x66, 0x6f,
	0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x41, 0x53, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0e, 0x53, 0x65, 0x6e,
	0x64, 0x4c, 0x42, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x42, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4c, 0x42, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_generated_proto_rawDescOnce sync.Once
	file_generated_proto_rawDescData = file_generated_proto_rawDesc
)

func file_generated_proto_rawDescGZIP() []byte {
	file_generated_proto_rawDescOnce.Do(func() {
		file_generated_proto_rawDescData = protoimpl.X.CompressGZIP(file_generated_proto_rawDescData)
	})
	return file_generated_proto_rawDescData
}

var file_generated_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_generated_proto_goTypes = []interface{}{
	(*HASInfo)(nil),       // 0: protobuf.HASInfo
	(*ResponseHAS)(nil),   // 1: protobuf.ResponseHAS
	(*LBInfo)(nil),        // 2: protobuf.LBInfo
	(*ResponseLB)(nil),    // 3: protobuf.ResponseLB
	(*SchedInfo)(nil),     // 4: protobuf.SchedInfo
	(*ResponseSched)(nil), // 5: protobuf.ResponseSched
	nil,                   // 6: protobuf.ResponseLB.ScoreMapEntry
}
var file_generated_proto_depIdxs = []int32{
	6, // 0: protobuf.ResponseLB.ScoreMap:type_name -> protobuf.ResponseLB.ScoreMapEntry
	0, // 1: protobuf.RequestAnalysis.SendHASMinAnalysis:input_type -> protobuf.HASInfo
	0, // 2: protobuf.RequestAnalysis.SendHASMaxAnalysis:input_type -> protobuf.HASInfo
	2, // 3: protobuf.RequestAnalysis.SendLBAnalysis:input_type -> protobuf.LBInfo
	4, // 4: protobuf.RequestAnalysis.SendSchedAnalysis:input_type -> protobuf.SchedInfo
	1, // 5: protobuf.RequestAnalysis.SendHASMinAnalysis:output_type -> protobuf.ResponseHAS
	1, // 6: protobuf.RequestAnalysis.SendHASMaxAnalysis:output_type -> protobuf.ResponseHAS
	3, // 7: protobuf.RequestAnalysis.SendLBAnalysis:output_type -> protobuf.ResponseLB
	5, // 8: protobuf.RequestAnalysis.SendSchedAnalysis:output_type -> protobuf.ResponseSched
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_generated_proto_init() }
func file_generated_proto_init() {
	if File_generated_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_generated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HASInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generated_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseHAS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generated_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LBInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generated_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseLB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generated_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generated_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseSched); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_generated_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generated_proto_goTypes,
		DependencyIndexes: file_generated_proto_depIdxs,
		MessageInfos:      file_generated_proto_msgTypes,
	}.Build()
	File_generated_proto = out.File
	file_generated_proto_rawDesc = nil
	file_generated_proto_goTypes = nil
	file_generated_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RequestAnalysisClient is the client API for RequestAnalysis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RequestAnalysisClient interface {
	SendHASMinAnalysis(ctx context.Context, in *HASInfo, opts ...grpc.CallOption) (*ResponseHAS, error)
	SendHASMaxAnalysis(ctx context.Context, in *HASInfo, opts ...grpc.CallOption) (*ResponseHAS, error)
	SendLBAnalysis(ctx context.Context, in *LBInfo, opts ...grpc.CallOption) (*ResponseLB, error)
	SendSchedAnalysis(ctx context.Context, in *SchedInfo, opts ...grpc.CallOption) (*ResponseSched, error)
}

type requestAnalysisClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestAnalysisClient(cc grpc.ClientConnInterface) RequestAnalysisClient {
	return &requestAnalysisClient{cc}
}

func (c *requestAnalysisClient) SendHASMinAnalysis(ctx context.Context, in *HASInfo, opts ...grpc.CallOption) (*ResponseHAS, error) {
	out := new(ResponseHAS)
	err := c.cc.Invoke(ctx, "/protobuf.RequestAnalysis/SendHASMinAnalysis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestAnalysisClient) SendHASMaxAnalysis(ctx context.Context, in *HASInfo, opts ...grpc.CallOption) (*ResponseHAS, error) {
	out := new(ResponseHAS)
	err := c.cc.Invoke(ctx, "/protobuf.RequestAnalysis/SendHASMaxAnalysis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestAnalysisClient) SendLBAnalysis(ctx context.Context, in *LBInfo, opts ...grpc.CallOption) (*ResponseLB, error) {
	out := new(ResponseLB)
	err := c.cc.Invoke(ctx, "/protobuf.RequestAnalysis/SendLBAnalysis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestAnalysisClient) SendSchedAnalysis(ctx context.Context, in *SchedInfo, opts ...grpc.CallOption) (*ResponseSched, error) {
	out := new(ResponseSched)
	err := c.cc.Invoke(ctx, "/protobuf.RequestAnalysis/SendSchedAnalysis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestAnalysisServer is the server API for RequestAnalysis service.
type RequestAnalysisServer interface {
	SendHASMinAnalysis(context.Context, *HASInfo) (*ResponseHAS, error)
	SendHASMaxAnalysis(context.Context, *HASInfo) (*ResponseHAS, error)
	SendLBAnalysis(context.Context, *LBInfo) (*ResponseLB, error)
	SendSchedAnalysis(context.Context, *SchedInfo) (*ResponseSched, error)
}

// UnimplementedRequestAnalysisServer can be embedded to have forward compatible implementations.
type UnimplementedRequestAnalysisServer struct {
}

func (*UnimplementedRequestAnalysisServer) SendHASMinAnalysis(context.Context, *HASInfo) (*ResponseHAS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHASMinAnalysis not implemented")
}
func (*UnimplementedRequestAnalysisServer) SendHASMaxAnalysis(context.Context, *HASInfo) (*ResponseHAS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHASMaxAnalysis not implemented")
}
func (*UnimplementedRequestAnalysisServer) SendLBAnalysis(context.Context, *LBInfo) (*ResponseLB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLBAnalysis not implemented")
}
func (*UnimplementedRequestAnalysisServer) SendSchedAnalysis(context.Context, *SchedInfo) (*ResponseSched, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSchedAnalysis not implemented")
}

func RegisterRequestAnalysisServer(s *grpc.Server, srv RequestAnalysisServer) {
	s.RegisterService(&_RequestAnalysis_serviceDesc, srv)
}

func _RequestAnalysis_SendHASMinAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HASInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestAnalysisServer).SendHASMinAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.RequestAnalysis/SendHASMinAnalysis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestAnalysisServer).SendHASMinAnalysis(ctx, req.(*HASInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestAnalysis_SendHASMaxAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HASInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestAnalysisServer).SendHASMaxAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.RequestAnalysis/SendHASMaxAnalysis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestAnalysisServer).SendHASMaxAnalysis(ctx, req.(*HASInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestAnalysis_SendLBAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LBInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestAnalysisServer).SendLBAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.RequestAnalysis/SendLBAnalysis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestAnalysisServer).SendLBAnalysis(ctx, req.(*LBInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestAnalysis_SendSchedAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestAnalysisServer).SendSchedAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.RequestAnalysis/SendSchedAnalysis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestAnalysisServer).SendSchedAnalysis(ctx, req.(*SchedInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _RequestAnalysis_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.RequestAnalysis",
	HandlerType: (*RequestAnalysisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHASMinAnalysis",
			Handler:    _RequestAnalysis_SendHASMinAnalysis_Handler,
		},
		{
			MethodName: "SendHASMaxAnalysis",
			Handler:    _RequestAnalysis_SendHASMaxAnalysis_Handler,
		},
		{
			MethodName: "SendLBAnalysis",
			Handler:    _RequestAnalysis_SendLBAnalysis_Handler,
		},
		{
			MethodName: "SendSchedAnalysis",
			Handler:    _RequestAnalysis_SendSchedAnalysis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "generated.proto",
}
