apiVersion:  openmcp.k8s.io/v1alpha1
kind: OpenMCPIngress
metadata:
  name: web-ingress-in
spec:
  template:
    spec:
      rules:
      - host: keti.web.openmcp.in
        http:
          paths:
          - backend:
              serviceName: web
              servicePort: 8080
