// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDeployment) DeepCopyInto(out *OpenMCPDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPDeployment.
func (in *OpenMCPDeployment) DeepCopy() *OpenMCPDeployment {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDeploymentList) DeepCopyInto(out *OpenMCPDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPDeploymentList.
func (in *OpenMCPDeploymentList) DeepCopy() *OpenMCPDeploymentList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDeploymentSpec) DeepCopyInto(out *OpenMCPDeploymentSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPDeploymentSpec.
func (in *OpenMCPDeploymentSpec) DeepCopy() *OpenMCPDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDeploymentStatus) DeepCopyInto(out *OpenMCPDeploymentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPDeploymentStatus.
func (in *OpenMCPDeploymentStatus) DeepCopy() *OpenMCPDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}
// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPIngress) DeepCopyInto(out *OpenMCPIngress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPIngress.
func (in *OpenMCPIngress) DeepCopy() *OpenMCPIngress {
	if in == nil {
		return nil
	}
	out := new(OpenMCPIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPIngress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPIngressList) DeepCopyInto(out *OpenMCPIngressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPIngress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPIngressList.
func (in *OpenMCPIngressList) DeepCopy() *OpenMCPIngressList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPIngressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPIngressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPIngressSpec) DeepCopyInto(out *OpenMCPIngressSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPIngressSpec.
func (in *OpenMCPIngressSpec) DeepCopy() *OpenMCPIngressSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPIngressStatus) DeepCopyInto(out *OpenMCPIngressStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPIngressStatus.
func (in *OpenMCPIngressStatus) DeepCopy() *OpenMCPIngressStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPIngressStatus)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPService) DeepCopyInto(out *OpenMCPService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPService.
func (in *OpenMCPService) DeepCopy() *OpenMCPService {
	if in == nil {
		return nil
	}
	out := new(OpenMCPService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPServiceList) DeepCopyInto(out *OpenMCPServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPServiceList.
func (in *OpenMCPServiceList) DeepCopy() *OpenMCPServiceList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPServiceSpec) DeepCopyInto(out *OpenMCPServiceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPServiceSpec.
func (in *OpenMCPServiceSpec) DeepCopy() *OpenMCPServiceSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPServiceStatus) DeepCopyInto(out *OpenMCPServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPServiceStatus.
func (in *OpenMCPServiceStatus) DeepCopy() *OpenMCPServiceStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPHybridAutoScaler) DeepCopyInto(out *OpenMCPHybridAutoScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPHybridAutoScaler.
func (in *OpenMCPHybridAutoScaler) DeepCopy() *OpenMCPHybridAutoScaler {
	if in == nil {
		return nil
	}
	out := new(OpenMCPHybridAutoScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPHybridAutoScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPHybridAutoScalerList) DeepCopyInto(out *OpenMCPHybridAutoScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPHybridAutoScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPHybridAutoScalerList.
func (in *OpenMCPHybridAutoScalerList) DeepCopy() *OpenMCPHybridAutoScalerList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPHybridAutoScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPHybridAutoScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPHybridAutoScalerSpec) DeepCopyInto(out *OpenMCPHybridAutoScalerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPHybridAutoScalerSpec.
func (in *OpenMCPHybridAutoScalerSpec) DeepCopy() *OpenMCPHybridAutoScalerSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPHybridAutoScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPHybridAutoScalerStatus) DeepCopyInto(out *OpenMCPHybridAutoScalerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPHybridAutoScalerStatus.
func (in *OpenMCPHybridAutoScalerStatus) DeepCopy() *OpenMCPHybridAutoScalerStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPHybridAutoScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPolicyEngine) DeepCopyInto(out *OpenMCPPolicyEngine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPPolicyEngine.
func (in *OpenMCPPolicyEngine) DeepCopy() *OpenMCPPolicyEngine {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPolicyEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPPolicyEngine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPolicyEngineList) DeepCopyInto(out *OpenMCPPolicyEngineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPPolicyEngine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPPolicyEngineList.
func (in *OpenMCPPolicyEngineList) DeepCopy() *OpenMCPPolicyEngineList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPolicyEngineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPPolicyEngineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPolicyEngineSpec) DeepCopyInto(out *OpenMCPPolicyEngineSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPPolicyEngineSpec.
func (in *OpenMCPPolicyEngineSpec) DeepCopy() *OpenMCPPolicyEngineSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPolicyEngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPolicyEngineStatus) DeepCopyInto(out *OpenMCPPolicyEngineStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPPolicyEngineStatus.
func (in *OpenMCPPolicyEngineStatus) DeepCopy() *OpenMCPPolicyEngineStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPolicyEngineStatus)
	in.DeepCopyInto(out)
	return out
}