apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kubeconfig
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/.kube
    server: "10.0.3.97"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-initmodule
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/workspace/Public_OpenMCP/install_openmcp/member
    server: "10.0.3.97"
    readOnly: false
