apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kubeconfig
  namespace: openmcp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: cluster-manager
  selector:
    matchLabels:
      app: kube-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-initmodule
  namespace: openmcp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: cluster-manager
  selector:
    matchLabels:
      app: initmodule
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aws-config
  namespace: openmcp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: cluster-manager
  selector:
    matchLabels:
      app: aws-config