apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmcp-policy-engine
  namespace: openmcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openmcp-policy-engine
  template:
    metadata:
      labels:
        name: openmcp-policy-engine
    spec:
      serviceAccountName: openmcp-policy-engine
      imagePullSecrets:
        - name: "regcred"
      containers:
        - name: openmcp-policy-engine
          # Replace this with the built image name
          image: ketidevit/openmcp-policy-engine:v0.0.1
          command:
          - openmcp-policy-engine
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              #value: ""
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "openmcp-policy-engine"
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
