apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: rest-proxy
  #namespace: smartcity
spec:
  replicas: 1
  clusters:
  - cluster10
  labels:
    app: rest-proxy
    affinity: "yes"
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - env:
                - name: KAFKA_REST_BOOTSTRAP_SERVERS
                  value: broker:29092
                - name: KAFKA_REST_HOST_NAME
                  value: rest-proxy
                - name: KAFKA_REST_LISTENERS
                  value: http://0.0.0.0:8082
              image: confluentinc/cp-kafka-rest:6.0.0
              name: rest-proxy
              ports:
                - containerPort: 8082
              #resources:
              #  requests:
              #    memory: 1Gi
              #    cpu: 1
              #    ephemeral-storage: 1Gi
          hostname: rest-proxy
          restartPolicy: Always
