apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeployment1
  namespace: openmcp
spec:
  replicas: 5
  affinity: 
    region: 
      - KR
    zone: 
      - Seoul
      - Gyeonggi-do
  labels:
      app: openmcp-nginx
      test: "yes"
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
            imagePullPolicy: IfNotPresent
            imagePullSecrets:
            - name: docker-registry-login
            resources:
              requests:
                memory: "100"
                cpu: "0.5"
