apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    cluster.local:53 {
      errors
      health
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        #upstream
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
      }
      prometheus :9153
      ready :8181
      forward . /etc/resolv.conf
      cache 30
      loop
      reload
      loadbalance
    }
    .:53 {
      errors
      cache 30
      forward . 115.94.141.62:5353
    }
