apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kubeconfig
  labels:
    app: kube-config
spec:
  capacity:
    storage: 2Gi
  storageClassName: cluster-manager
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/.kube
    server: REPLACE_OMCPIP
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-initmodule
  labels:
    app: initmodule
spec:
  capacity:
    storage: 2Gi
  storageClassName: cluster-manager
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    #path: /root/workspace/Public_OpenMCP/install_openmcp/member
    path: REPLACE_INIT_MEMBER_DIR
    server: REPLACE_OMCPIP
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-aws-config
  labels:
    app: aws-config
spec:
  capacity:
    storage: 2Gi
  storageClassName: cluster-manager
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/.aws
    server: REPLACE_OMCPIP
    readOnly: false
