apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kubeconfig
  namespace: openmcp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-initmodule
  namespace: openmcp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
