// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDeployment) DeepCopyInto(out *OpenMCPDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPDeployment.
func (in *OpenMCPDeployment) DeepCopy() *OpenMCPDeployment {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDeploymentList) DeepCopyInto(out *OpenMCPDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPDeploymentList.
func (in *OpenMCPDeploymentList) DeepCopy() *OpenMCPDeploymentList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDeploymentSpec) DeepCopyInto(out *OpenMCPDeploymentSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPDeploymentSpec.
func (in *OpenMCPDeploymentSpec) DeepCopy() *OpenMCPDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDeploymentStatus) DeepCopyInto(out *OpenMCPDeploymentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPDeploymentStatus.
func (in *OpenMCPDeploymentStatus) DeepCopy() *OpenMCPDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPIngress) DeepCopyInto(out *OpenMCPIngress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPIngress.
func (in *OpenMCPIngress) DeepCopy() *OpenMCPIngress {
	if in == nil {
		return nil
	}
	out := new(OpenMCPIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPIngress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPIngressList) DeepCopyInto(out *OpenMCPIngressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPIngress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPIngressList.
func (in *OpenMCPIngressList) DeepCopy() *OpenMCPIngressList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPIngressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPIngressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPIngressSpec) DeepCopyInto(out *OpenMCPIngressSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPIngressSpec.
func (in *OpenMCPIngressSpec) DeepCopy() *OpenMCPIngressSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPIngressStatus) DeepCopyInto(out *OpenMCPIngressStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPIngressStatus.
func (in *OpenMCPIngressStatus) DeepCopy() *OpenMCPIngressStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPIngressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPService) DeepCopyInto(out *OpenMCPService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPService.
func (in *OpenMCPService) DeepCopy() *OpenMCPService {
	if in == nil {
		return nil
	}
	out := new(OpenMCPService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPServiceList) DeepCopyInto(out *OpenMCPServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPServiceList.
func (in *OpenMCPServiceList) DeepCopy() *OpenMCPServiceList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPServiceSpec) DeepCopyInto(out *OpenMCPServiceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPServiceSpec.
func (in *OpenMCPServiceSpec) DeepCopy() *OpenMCPServiceSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPServiceStatus) DeepCopyInto(out *OpenMCPServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPServiceStatus.
func (in *OpenMCPServiceStatus) DeepCopy() *OpenMCPServiceStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPHybridAutoScaler) DeepCopyInto(out *OpenMCPHybridAutoScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPHybridAutoScaler.
func (in *OpenMCPHybridAutoScaler) DeepCopy() *OpenMCPHybridAutoScaler {
	if in == nil {
		return nil
	}
	out := new(OpenMCPHybridAutoScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPHybridAutoScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPHybridAutoScalerList) DeepCopyInto(out *OpenMCPHybridAutoScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPHybridAutoScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPHybridAutoScalerList.
func (in *OpenMCPHybridAutoScalerList) DeepCopy() *OpenMCPHybridAutoScalerList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPHybridAutoScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPHybridAutoScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPHybridAutoScalerSpec) DeepCopyInto(out *OpenMCPHybridAutoScalerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPHybridAutoScalerSpec.
func (in *OpenMCPHybridAutoScalerSpec) DeepCopy() *OpenMCPHybridAutoScalerSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPHybridAutoScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPHybridAutoScalerStatus) DeepCopyInto(out *OpenMCPHybridAutoScalerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPHybridAutoScalerStatus.
func (in *OpenMCPHybridAutoScalerStatus) DeepCopy() *OpenMCPHybridAutoScalerStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPHybridAutoScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPConfigMap) DeepCopyInto(out *OpenMCPConfigMap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPConfigMap.
func (in *OpenMCPConfigMap) DeepCopy() *OpenMCPConfigMap {
	if in == nil {
		return nil
	}
	out := new(OpenMCPConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPConfigMap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPConfigMapList) DeepCopyInto(out *OpenMCPConfigMapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPConfigMap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPConfigMapList.
func (in *OpenMCPConfigMapList) DeepCopy() *OpenMCPConfigMapList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPConfigMapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPConfigMapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPConfigMapSpec) DeepCopyInto(out *OpenMCPConfigMapSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPConfigMapSpec.
func (in *OpenMCPConfigMapSpec) DeepCopy() *OpenMCPConfigMapSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPConfigMapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPConfigMapStatus) DeepCopyInto(out *OpenMCPConfigMapStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPConfigMapStatus.
func (in *OpenMCPConfigMapStatus) DeepCopy() *OpenMCPConfigMapStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPConfigMapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPSecret) DeepCopyInto(out *OpenMCPSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPSecret.
func (in *OpenMCPSecret) DeepCopy() *OpenMCPSecret {
	if in == nil {
		return nil
	}
	out := new(OpenMCPSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPSecretList) DeepCopyInto(out *OpenMCPSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPSecretList.
func (in *OpenMCPSecretList) DeepCopy() *OpenMCPSecretList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPSecretSpec) DeepCopyInto(out *OpenMCPSecretSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPSecretSpec.
func (in *OpenMCPSecretSpec) DeepCopy() *OpenMCPSecretSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPSecretStatus) DeepCopyInto(out *OpenMCPSecretStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPSecretStatus.
func (in *OpenMCPSecretStatus) DeepCopy() *OpenMCPSecretStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPJob) DeepCopyInto(out *OpenMCPJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJob.
func (in *OpenMCPJob) DeepCopy() *OpenMCPJob {
	if in == nil {
		return nil
	}
	out := new(OpenMCPJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPJobList) DeepCopyInto(out *OpenMCPJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobList.
func (in *OpenMCPJobList) DeepCopy() *OpenMCPJobList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPJobSpec) DeepCopyInto(out *OpenMCPJobSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobSpec.
func (in *OpenMCPJobSpec) DeepCopy() *OpenMCPJobSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPJobStatus) DeepCopyInto(out *OpenMCPJobStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobStatus.
func (in *OpenMCPJobStatus) DeepCopy() *OpenMCPJobStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPNamespace) DeepCopyInto(out *OpenMCPNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPNamespace.
func (in *OpenMCPNamespace) DeepCopy() *OpenMCPNamespace {
	if in == nil {
		return nil
	}
	out := new(OpenMCPNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPNamespaceList) DeepCopyInto(out *OpenMCPNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPNamespaceList.
func (in *OpenMCPNamespaceList) DeepCopy() *OpenMCPNamespaceList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPNamespaceSpec) DeepCopyInto(out *OpenMCPNamespaceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPNamespaceSpec.
func (in *OpenMCPNamespaceSpec) DeepCopy() *OpenMCPNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPNamespaceStatus) DeepCopyInto(out *OpenMCPNamespaceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPNamespaceStatus.
func (in *OpenMCPNamespaceStatus) DeepCopy() *OpenMCPNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPVirtualService) DeepCopyInto(out *OpenMCPVirtualService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPVirtualService.
func (in *OpenMCPVirtualService) DeepCopy() *OpenMCPVirtualService {
	if in == nil {
		return nil
	}
	out := new(OpenMCPVirtualService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPVirtualService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPVirtualServiceList) DeepCopyInto(out *OpenMCPVirtualServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPVirtualService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPVirtualServiceList.
func (in *OpenMCPVirtualServiceList) DeepCopy() *OpenMCPVirtualServiceList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPVirtualServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPVirtualServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPersistentVolumeClaim) DeepCopyInto(out *OpenMCPPersistentVolumeClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJob.
func (in *OpenMCPPersistentVolumeClaim) DeepCopy() *OpenMCPPersistentVolumeClaim {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPersistentVolumeClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPPersistentVolumeClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPersistentVolumeClaimList) DeepCopyInto(out *OpenMCPPersistentVolumeClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPPersistentVolumeClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobList.
func (in *OpenMCPPersistentVolumeClaimList) DeepCopy() *OpenMCPPersistentVolumeClaimList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPersistentVolumeClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPPersistentVolumeClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPersistentVolumeClaimSpec) DeepCopyInto(out *OpenMCPPersistentVolumeClaimSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobSpec.
func (in *OpenMCPPersistentVolumeClaimSpec) DeepCopy() *OpenMCPPersistentVolumeClaimSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPersistentVolumeClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPersistentVolumeClaimStatus) DeepCopyInto(out *OpenMCPPersistentVolumeClaimStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobStatus.
func (in *OpenMCPPersistentVolumeClaimStatus) DeepCopy() *OpenMCPPersistentVolumeClaimStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPersistentVolumeClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPersistentVolume) DeepCopyInto(out *OpenMCPPersistentVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJob.
func (in *OpenMCPPersistentVolume) DeepCopy() *OpenMCPPersistentVolume {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPersistentVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPPersistentVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPersistentVolumeList) DeepCopyInto(out *OpenMCPPersistentVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPPersistentVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobList.
func (in *OpenMCPPersistentVolumeList) DeepCopy() *OpenMCPPersistentVolumeList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPersistentVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPPersistentVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPersistentVolumeSpec) DeepCopyInto(out *OpenMCPPersistentVolumeSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobSpec.
func (in *OpenMCPPersistentVolumeSpec) DeepCopy() *OpenMCPPersistentVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPersistentVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPPersistentVolumeStatus) DeepCopyInto(out *OpenMCPPersistentVolumeStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobStatus.
func (in *OpenMCPPersistentVolumeStatus) DeepCopy() *OpenMCPPersistentVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPPersistentVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPStatefulSet) DeepCopyInto(out *OpenMCPStatefulSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJob.
func (in *OpenMCPStatefulSet) DeepCopy() *OpenMCPStatefulSet {
	if in == nil {
		return nil
	}
	out := new(OpenMCPStatefulSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPStatefulSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPStatefulSetList) DeepCopyInto(out *OpenMCPStatefulSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPStatefulSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobList.
func (in *OpenMCPStatefulSetList) DeepCopy() *OpenMCPStatefulSetList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPStatefulSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPStatefulSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPStatefulSetSpec) DeepCopyInto(out *OpenMCPStatefulSetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobSpec.
func (in *OpenMCPStatefulSetSpec) DeepCopy() *OpenMCPStatefulSetSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPStatefulSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPStatefulSetStatus) DeepCopyInto(out *OpenMCPStatefulSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobStatus.
func (in *OpenMCPStatefulSetStatus) DeepCopy() *OpenMCPStatefulSetStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPStatefulSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDaemonSet) DeepCopyInto(out *OpenMCPDaemonSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJob.
func (in *OpenMCPDaemonSet) DeepCopy() *OpenMCPDaemonSet {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDaemonSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPDaemonSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDaemonSetList) DeepCopyInto(out *OpenMCPDaemonSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMCPDaemonSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobList.
func (in *OpenMCPDaemonSetList) DeepCopy() *OpenMCPDaemonSetList {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDaemonSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMCPDaemonSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDaemonSetSpec) DeepCopyInto(out *OpenMCPDaemonSetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobSpec.
func (in *OpenMCPDaemonSetSpec) DeepCopy() *OpenMCPDaemonSetSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDaemonSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMCPDaemonSetStatus) DeepCopyInto(out *OpenMCPDaemonSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMCPJobStatus.
func (in *OpenMCPDaemonSetStatus) DeepCopy() *OpenMCPDaemonSetStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMCPDaemonSetStatus)
	in.DeepCopyInto(out)
	return out
}
