apiVersion: v1
kind: PersistentVolume
metadata:
  name: 200gi-a09
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/nfs/pv/200Gi/a09
    server: "10.0.3.12"
    readOnly: false
