apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPVirtualService
metadata:
  name: wordpress
  namespace: wordpress
spec:
  hosts:
  - "keti.wordpress.openmcp.in"
  gateways:
  - istio-ingress-gateway
  http:
  - match:
    - uri:
       prefix: /
#    - uri:
#      prefix: /wp-admin
#    - uri:
#       prefix: /wp-includes
#    - uri:
#       prefix: /wp-login.php
    route:
    - destination:
        host: wordpress-cpa
        port:
          number: 80
