#!/bin/bash

if [[ "$1" == "GKE" ]] || [[ "$1" == "EKS" ]] || [[ "$1" == "AKS" ]]; then
  echo "Cloud Cluster"
else
  echo "Error : Input Cloud Cluster Type"
  echo "ex) kubectl register gke-cluster1 openmcp:8080"
  exit 1
fi

if [ "$2" = "" ]; then
  echo "Error : Input Cluster Name"
  echo "ex) kubectl register gke-cluster1 openmcp:8080"
  exit 1
fi

if [ "$3" = "" ]; then
  echo "Error : Input OpenMCP IP:PORT"
  echo "ex) kubectl register gke-cluster1 openmcp:8080"
  exit 1
fi

touch kubeconfig
export KUBECONFIG=./kubeconfig

if [ "$1" == "GKE" ]; then
  gcloud container clusters get-credentials $2
  kubectl get pods &>-
  rm -
elif [ "$1" == "EKS" ]; then
  aws eks update-kubeconfig --name $2
elif [ "$1" == "AKS" ]; then
  az aks get-credentials --resource-group openmcpResourceGroup --name $2 --file ./kubeconfig
fi

export KUBECONFIG=~/.kube/config
echo -n | openssl s_client -connect $3 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > server.crt
curl -F file=@"kubeconfig" "https://$3/joinCloud?clustername=$2&clustertype=$1" --cacert server.crt
rm server.crt
rm kubeconfig
