apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPHybridAutoScaler
metadata:
  name: test-has-php
  namespace: test
spec:
  mainController: OpenMCP
  scalingOptions:
    cpaTemplate:
      scaleTargetRef:
        kind: OpenMCPDeployment
        name: test-odeploy-php
      minReplicas: 1
      maxReplicas: 6
