apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPersistentVolumeClaim
metadata:
  name: mysql-volumeclaim
  namespace: wordpress
spec:
  clusters:
    - cluster03
    - cluster09
    - cluster14
  template:
    spec:
      storageClassName: mysql
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
