apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPersistentVolume
metadata:
  name: pv001
  labels:
    type: local
spec:
  clusters:
  - cluster01
  - cluster02
  - cluster03
  labels:
    type: local
  template:
    spec:
      storageClassName: mysql
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteOnce
      nfs:
        path: /wordpress/data001/pv001
        #server: "211.45.109.210"
        server: "115.94.141.62"
        readOnly: false
