apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPersistentVolume
metadata:
  name: pv002
  labels:
    type: local
spec:
  clusters:
    - cluster03
    - cluster09
    - cluster14
  labels:
    type: local
  template:
    spec:
      storageClassName: wp
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteOnce
      nfs:
        path: /wordpress/data001/pv002
        #server: "10.0.3.20"
        server: "115.94.141.62"
        readOnly: false
