apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: mysql-cpa
  namespace: wordpress
  labels:
    app: mysql-cpa
spec:
  template:
    spec:
      type: ClusterIP
      ports:
      - port: 3306
      selector:
        app: mysql-cpa

