apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPersistentVolumeClaim
metadata:
  name: post-pvc-claim1
  #namespace: smartcity
  namespace: default
spec:
  template:
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: postgis
      resources:
        requests:
          storage: 2Gi
