kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv002
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/nfs/wordpress/data001/pv002
    server: "10.0.3.20"
    readOnly: false

