apiVersion:  openmcp.k8s.io/v1alpha1
kind: OpenMCPIngress
metadata:
  name: openmcp-ingress-keti
spec:
  template:
    spec:
      rules:
        - host: openmcp.keti.org
          http:
            paths:
              - backend:
#                  serviceName: iot-gateway-svc
#                  servicePort: 8888
              - backend:
                  serviceName: iot-gateway-svc
                  servicePort: 80