apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPServiceDNSRecord
metadata:
  # The name of the sample service.
  name: iot-gateway-svc
  # The namespace of the sample deployment/service.
spec:
  # The name of the corresponding Domain.
  domainRef: openmcp-keti-domain
  recordTTL: 300

