apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: web
  namespace: smartcity
  labels:
    app: web
spec:
  template:
    spec:
      type: LoadBalancer
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
          nodePort: 30035
      selector:
        app: web