// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: generated.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HpaInfo []*OpenMCPHPAInfo `protobuf:"bytes,1,rep,name=HpaInfo,proto3" json:"HpaInfo,omitempty"`
}

func (x *RequestValue) Reset() {
	*x = RequestValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestValue) ProtoMessage() {}

func (x *RequestValue) ProtoReflect() protoreflect.Message {
	mi := &file_generated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestValue.ProtoReflect.Descriptor instead.
func (*RequestValue) Descriptor() ([]byte, []int) {
	return file_generated_proto_rawDescGZIP(), []int{0}
}

func (x *RequestValue) GetHpaInfo() []*OpenMCPHPAInfo {
	if x != nil {
		return x.HpaInfo
	}
	return nil
}

type OpenMCPHPAInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeploymentName      string         `protobuf:"bytes,1,opt,name=DeploymentName,proto3" json:"DeploymentName,omitempty"`
	DeploymentNamespace string         `protobuf:"bytes,2,opt,name=DeploymentNamespace,proto3" json:"DeploymentNamespace,omitempty"`
	CL                  []*ClusterList `protobuf:"bytes,3,rep,name=CL,proto3" json:"CL,omitempty"`
}

func (x *OpenMCPHPAInfo) Reset() {
	*x = OpenMCPHPAInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generated_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenMCPHPAInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenMCPHPAInfo) ProtoMessage() {}

func (x *OpenMCPHPAInfo) ProtoReflect() protoreflect.Message {
	mi := &file_generated_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenMCPHPAInfo.ProtoReflect.Descriptor instead.
func (*OpenMCPHPAInfo) Descriptor() ([]byte, []int) {
	return file_generated_proto_rawDescGZIP(), []int{1}
}

func (x *OpenMCPHPAInfo) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *OpenMCPHPAInfo) GetDeploymentNamespace() string {
	if x != nil {
		return x.DeploymentNamespace
	}
	return ""
}

func (x *OpenMCPHPAInfo) GetCL() []*ClusterList {
	if x != nil {
		return x.CL
	}
	return nil
}

type ClusterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterName string `protobuf:"bytes,1,opt,name=ClusterName,proto3" json:"ClusterName,omitempty"`
}

func (x *ClusterList) Reset() {
	*x = ClusterList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generated_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterList) ProtoMessage() {}

func (x *ClusterList) ProtoReflect() protoreflect.Message {
	mi := &file_generated_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterList.ProtoReflect.Descriptor instead.
func (*ClusterList) Descriptor() ([]byte, []int) {
	return file_generated_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterList) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type ResponseValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetCluster string `protobuf:"bytes,1,opt,name=TargetCluster,proto3" json:"TargetCluster,omitempty"`
}

func (x *ResponseValue) Reset() {
	*x = ResponseValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generated_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseValue) ProtoMessage() {}

func (x *ResponseValue) ProtoReflect() protoreflect.Message {
	mi := &file_generated_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseValue.ProtoReflect.Descriptor instead.
func (*ResponseValue) Descriptor() ([]byte, []int) {
	return file_generated_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseValue) GetTargetCluster() string {
	if x != nil {
		return x.TargetCluster
	}
	return ""
}

var File_generated_proto protoreflect.FileDescriptor

var file_generated_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x42, 0x0a, 0x0c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x48,
	0x70, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x4d, 0x43, 0x50, 0x48,
	0x50, 0x41, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x48, 0x70, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x91, 0x01, 0x0a, 0x0e, 0x4f, 0x70, 0x65, 0x6e, 0x4d, 0x43, 0x50, 0x48, 0x50, 0x41, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x02,
	0x43, 0x4c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x02, 0x43, 0x4c, 0x22, 0x2f, 0x0a, 0x0b, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x32, 0x5d, 0x0a, 0x12, 0x53,
	0x65, 0x6e, 0x64, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x47, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_generated_proto_rawDescOnce sync.Once
	file_generated_proto_rawDescData = file_generated_proto_rawDesc
)

func file_generated_proto_rawDescGZIP() []byte {
	file_generated_proto_rawDescOnce.Do(func() {
		file_generated_proto_rawDescData = protoimpl.X.CompressGZIP(file_generated_proto_rawDescData)
	})
	return file_generated_proto_rawDescData
}

var file_generated_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_generated_proto_goTypes = []interface{}{
	(*RequestValue)(nil),   // 0: protobuf.RequestValue
	(*OpenMCPHPAInfo)(nil), // 1: protobuf.OpenMCPHPAInfo
	(*ClusterList)(nil),    // 2: protobuf.ClusterList
	(*ResponseValue)(nil),  // 3: protobuf.ResponseValue
}
var file_generated_proto_depIdxs = []int32{
	1, // 0: protobuf.RequestValue.HpaInfo:type_name -> protobuf.OpenMCPHPAInfo
	2, // 1: protobuf.OpenMCPHPAInfo.CL:type_name -> protobuf.ClusterList
	0, // 2: protobuf.SendAnalysisResult.SendAnalysisResult:input_type -> protobuf.RequestValue
	3, // 3: protobuf.SendAnalysisResult.SendAnalysisResult:output_type -> protobuf.ResponseValue
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_generated_proto_init() }
func file_generated_proto_init() {
	if File_generated_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_generated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generated_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenMCPHPAInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generated_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generated_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_generated_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generated_proto_goTypes,
		DependencyIndexes: file_generated_proto_depIdxs,
		MessageInfos:      file_generated_proto_msgTypes,
	}.Build()
	File_generated_proto = out.File
	file_generated_proto_rawDesc = nil
	file_generated_proto_goTypes = nil
	file_generated_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SendAnalysisResultClient is the client API for SendAnalysisResult service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendAnalysisResultClient interface {
	SendAnalysisResult(ctx context.Context, in *RequestValue, opts ...grpc.CallOption) (*ResponseValue, error)
}

type sendAnalysisResultClient struct {
	cc grpc.ClientConnInterface
}

func NewSendAnalysisResultClient(cc grpc.ClientConnInterface) SendAnalysisResultClient {
	return &sendAnalysisResultClient{cc}
}

func (c *sendAnalysisResultClient) SendAnalysisResult(ctx context.Context, in *RequestValue, opts ...grpc.CallOption) (*ResponseValue, error) {
	out := new(ResponseValue)
	err := c.cc.Invoke(ctx, "/protobuf.SendAnalysisResult/SendAnalysisResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendAnalysisResultServer is the server API for SendAnalysisResult service.
type SendAnalysisResultServer interface {
	SendAnalysisResult(context.Context, *RequestValue) (*ResponseValue, error)
}

// UnimplementedSendAnalysisResultServer can be embedded to have forward compatible implementations.
type UnimplementedSendAnalysisResultServer struct {
}

func (*UnimplementedSendAnalysisResultServer) SendAnalysisResult(context.Context, *RequestValue) (*ResponseValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAnalysisResult not implemented")
}

func RegisterSendAnalysisResultServer(s *grpc.Server, srv SendAnalysisResultServer) {
	s.RegisterService(&_SendAnalysisResult_serviceDesc, srv)
}

func _SendAnalysisResult_SendAnalysisResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendAnalysisResultServer).SendAnalysisResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SendAnalysisResult/SendAnalysisResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendAnalysisResultServer).SendAnalysisResult(ctx, req.(*RequestValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendAnalysisResult_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.SendAnalysisResult",
	HandlerType: (*SendAnalysisResultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAnalysisResult",
			Handler:    _SendAnalysisResult_SendAnalysisResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "generated.proto",
}
