apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPStatefulSet
metadata:
  name: oss-test
spec:
  clusters:
    - cluster01
  labels:
    app: oss-test
  template:
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: oss-test
      serviceName: postgis
      template:
        metadata:
          labels:
            app: oss-test
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - env:
                - name: POSTGRES_DBNAME
                  value: smart_city
                - name: POSTGRES_PASS
                  value: postgres
                - name: POSTGRES_USER
                  value: postgres
              image: kartoza/postgis:11.0-2.5
              name: postgis4
              ports:
                - containerPort: 5432
