apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: has-target-cluster
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: OpenMCPControler
      policies:
        - type: Target
          value:
            - cluster1
            - cluster2
            - cluster3
  rangeOfApplication: All
  policyStatus: Enabled
