apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
   defaultConfig:
     proxyMetadata:
       ISTIO_META_DNS_CAPTURE: "true"
  values:
    global:
      meshID: mesh-cluster10
      multiCluster:
        clusterName: cluster10
      network: network-cluster10
