apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
   defaultConfig:
     proxyMetadata:
       ISTIO_META_DNS_CAPTURE: "true"
  values:
    global:
      meshID: mesh-openmcp
      multiCluster:
        clusterName: openmcp
      network: network-openmcp
#  components:
#    ingressGateways:
#      - name: istio-ingressgateway
#        enabled: true
#        k8s:
#          service:
#            ports:
#              # We have to specify original ports otherwise it will be erased
#              - name: status-port
#                nodePort: 32569
#                port: 15022
#                protocol: TCP
#                targetPort: 15021
#              - name: http2
#                nodePort: 32223
#                port: 8011
#                protocol: TCP
#                targetPort: 8080
#              - name: https
#                nodePort: 30269
#                port: 444
#                protocol: TCP
#                targetPort: 8443
#              - name: tcp-istiod
#                nodePort: 31420
#                port: 15013
#                protocol: TCP
#                targetPort: 15012
#              - name: tls
#                nodePort: 31213
#                port: 15444
#                protocol: TCP
#                targetPort: 15443
#      - name: istio-eastwestgateway
#        enabled: true
#        k8s:
#          service:
#            ports:
#              # We have to specify original ports otherwise it will be erased
#              - name: status-port
#                nodePort: 31048
#                port: 15022
#                protocol: TCP
#                targetPort: 15021
#              - name: tls
#                nodePort: 30849
#                port: 15444
#                protocol: TCP
#                targetPort: 15443
#                - name: tls-istiod
#                nodePort: 30959
#                port: 15013
#                protocol: TCP
#                targetPort: 15012
#                - name: tls-webhook
#                nodePort: 30885
#                port: 15017
#                protocol: TCP
#                targetPort: 15017
