apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDaemonSet
metadata:
  name: ods-test
spec:
  clusters:
    - cluster01
  labels:
    app: ods-test
    k8s-app: fluentd-logging
  template:
    spec:
      selector:
        matchLabels:
          name: fluentd-elasticsearch
      template:
        metadata:
          labels:
             name: fluentd-elasticsearch
        spec:
          tolerations:
            - key: node-role.kubernetes.io/master
              effect: NoSchedule
          containers:
            - name: fluentd-elasticsearch
              image: k8s.gcr.io/fluentd-elasticsearch:1.20
              resources:
                limits:
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi