apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  template:
    spec:
      type: NodePort
      ports:
#        - name: port-1
#          port: 8080
#          protocol: TCP
#          targetPort: 8080
        - port: 8021
          targetPort: 7070
          name: http-sysbench
          nodePort: 32132
        - name: http-wordpress
          port: 80
          protocol: TCP
          targetPort: 80
          nodePort: 31188
      selector:
        app: wordpress
