apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: ingest
  namespace: smartcity
  labels:
    app: ingest
spec:
  template:
    spec:
      ports:
        - name: "8888"
          port: 8888
          targetPort: 8888
      selector:
        app: ingest