apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: user-tool
  namespace: smartcity
spec:
  replicas: 1
  clusters:
  - cluster11
  labels:
    app: user-tool
    affinity: "yes"
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - env:
                - name: DATACOREUSERTOOL_URL
                  value: http://user-tool:8083/notification
                - name: DATAMANAGER_URL
                  value: http://data-manager:8080
                - name: DATASERVICEBROKER_URL
                  value: http://data-service-broker:8082
                - name: SECURITY_ENABLED
                  value: "false"
              image: ketidevit/datacore-usertool:0.0.1
              imagePullPolicy: Always
              name: user-tool
              ports:
                - containerPort: 38081
              resources: {}
          restartPolicy: Always
