apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: user-tool
  namespace: smartcity
  labels:
    app: user-tool
spec:
  template:
    spec:
      type: LoadBalancer
      ports:
        - name: "8083"
          port: 8083
          targetPort: 38081
          nodePort: 30036
      selector:
        app: user-tool