apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmcp-scheduler
  namespace: openmcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openmcp-scheduler
  template:
    metadata:
      labels:
        name: openmcp-scheduler
    spec:
      serviceAccountName: openmcp-scheduler
      imagePullSecrets:
        - name: REPLACE_DOCKERSECRETNAME
      containers:
        - name: openmcp-scheduler
          # Replace this with the built image name
          image: ketidevit/openmcp-scheduler:v0.0.1
          command:
          - openmcp-scheduler
          imagePullPolicy: REPLACE_DOCKERIMAGEPULLPOLICY
          env:
            - name: WATCH_NAMESPACE
              #value: ""
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GRPC_SERVER
              value: REPLACE_GRPCIP
            - name: GRPC_PORT
              value: REPLACE_GRPCPORT
            - name: OPERATOR_NAME
              value: "openmcp-scheduler"
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
