apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmcp-metric-collector
  namespace: openmcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openmcp-metric-collector
  template:
    metadata:
      labels:
        name: openmcp-metric-collector
    spec:
      serviceAccountName: openmcp-metric-collector
      imagePullSecrets:
        - name: REPLACE_DOCKERSECRETNAME
      containers:
        - name: openmcp-metric-collector
          # Replace this with the built image name
          image: ketidevit/openmcp-metric-collector:v0.0.1
          command:
          - openmcp-metric-collector
          imagePullPolicy: REPLACE_DOCKERIMAGEPULLPOLICY
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INFLUX_IP
              value: REPLACE_INFLUXDBIP
            - name: INFLUX_PORT
              value: REPLACE_INFLUXDBPORT
            - name: INFLUX_USERNAME
              value: "root"
            - name: INFLUX_PASSWORD
              value: "root"
            - name: OPERATOR_NAME
              value: "openmcp-metric-collector"
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0

