apiVersion: v1
kind: Service
metadata:
  name: openmcp-loadbalancing-controller
  namespace: openmcp
spec:
  selector:
    name: openmcp-loadbalancing-controller
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Local
