apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: data-service-broker
  namespace: smartcity
spec:
  replicas: 1
  clusters:
  - cluster10
  labels:
    app: data-service-broker
    affinity: "yes"
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - env:
                - name: DATASOURCE_SECONDARY_URL
                  value: jdbc:postgresql://postgis:5432/smart_city
                - name: DATASOURCE_URL
                  value: jdbc:postgresql://postgis:5432/smart_city
                - name: KAFKA_URL
                  value: broker:29092
                - name: SECURITY_USEYN
                  value: "N"
              image: ketidevit/data-service-broker:0.0.1
              imagePullPolicy: Always
              name: data-service-broker
              ports:
                - containerPort: 8082
              resources: {}
          restartPolicy: Always
