apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: data-manager
  namespace: smartcity
spec:
  replicas: 1
  clusters:
  - cluster05
  labels:
    app: data-manager
    affinity: "yes"
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - env:
                - name: DATASOURCE_SECONDARY_URL
                  value: jdbc:postgresql://postgis:5432/smart_city
                - name: DATASOURCE_URL
                  value: jdbc:postgresql://postgis:5432/smart_city
                - name: KAFKA_URL
                  value: broker:29092
                - name: REST_PROXY_URL
                  value: http://rest-proxy:8082
                - name: SECURITY_USEYN
                  value: "N"
              image: ketidevit/data-manager:0.0.1
              imagePullPolicy: Always
              name: data-manager
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
