apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: scheduling-policy
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: OpenMCPSchduler
      policies:
        - type: algorithm
          value:
            - RR
  rangeOfApplication: All
  policyStatus: Enabled
---
apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: log-level
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: All-OpenMCP-Resource-Controller
      policies:
        - type: Level
          value:
            - "1"
  policyStatus: Enabled
---
apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: cpa-period
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: OpenMCPHybridAutoScaler
      policies:
        - type: period
          value:
            - "100"
  policyStatus: Enabled
