apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: broker
  namespace: smartcity
  #namespace: default
spec:
  replicas: 1
  clusters:
  - cluster05
  - cluster10
  - cluster12
  - cluster17
  labels:
    app: broker
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - env:
                - name: KAFKA_ADVERTISED_LISTENERS
                  value: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
                - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
                  value: "true"
                - name: KAFKA_BROKER_ID
                  value: "1"
                - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
                  value: "0"
                - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                  value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
                - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                  value: "1"
                - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
                  value: "1"
                - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
                  value: "1"
                - name: KAFKA_ZOOKEEPER_CONNECT
                  value: zookeeper:2181
              image: confluentinc/cp-kafka:6.0.0
              name: broker
              ports:
                - containerPort: 29092
                - containerPort: 9092
              #resources:
              #  requests:
              #    memory: 1Gi
              #    cpu: 1
              #    ephemeral-storage: 1Gi
          hostname: broker
          restartPolicy: Always
