apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: broker
  #namespace: smartcity
  namespace: default
  labels:
    app: broker
spec:
  template:
    spec:
      #type: NodePort
      ports:
        - name: "29092"
          port: 29092
          targetPort: 29092
        - name: "9092"
          port: 9092
          targetPort: 9092
          #nodePort: 30092
      selector:
        app: broker