apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: http-generator
spec:
  replicas: 10
  labels:
    app: http-generator
    component: http-generator
  template:
    spec:
      template:
        spec:
          #securityContext:
            #runAsUser: 1001
            #fsGroup: 1001
          containers:
          - name: http-generator
            #imagePullPolicy: IfNotPresent
            imagePullPolicy: Always
            image: openmcp/keti-http-generator:v1.1
            command: ["/app/start_http.sh"]
            resources:
              requests:
                memory: 256M
                cpu: 125m
              limits:
                memory: 256M
                cpu: 125m
            env:
            - name: COMPANY_NAME
              value: "SHINHAN"
            - name: CRANE_NAME
              value: "Crane_1"
            - name: IOT_GATEWAY_IP
              #value: "iot-gateway-svc.default.svc.cluster.local"
              #value: "iot-gateway-svc.default.openmcp-dt-domain.svc.openmcp.dt.org"
              value: "openmcp.dt.org"
            - name: HTTP_PORT
              #value: "8888"
              value: "80"
            - name: GEN_PERIOD_SEC
              value: "3"
          imagePullSecrets:
          - name: regcred
