#!/bin/bash

cat <<EOF > kubectl-join_status
#!/bin/bash
if [ "\$1" == "" ]; then
  echo "Please Input Cluster Name"
  echo "ex) kubectl join-status cluster1 JOIN"
  exit 1
fi

if [[ "\$2" == "JOIN" ]] || [[ "\$2" == "UNJOIN" ]] || [[ "\$2" == "STANDBY" ]]; then
  echo "Change Cluster Status [ \$2 ]"
else
  echo "Please Input Cluster Join Status (JOIN/UNJOIN)"
  echo "ex) kubectl join-status cluster1 JOIN"
  exit 1
fi

if [ "\$2" == "JOIN" ]; then
  read -p "Input MetalLB IP Address Range (FROM) : " address_from
  read -p "Input MetalLB IP Address Range (TO) : " address_to
fi

kubectl get openmcpcluster \$1 -n openmcp -o yaml | sed "s/IP_ADDRESS_FROM/\$address_from/g" | kubectl replace -f -
kubectl get openmcpcluster \$1 -n openmcp -o yaml | sed "s/IP_ADDRESS_TO/\$address_to/g" | kubectl replace -f -

if [ "\$2" == "JOIN" ]; then
  kubectl get openmcpcluster \$1 -n openmcp -o yaml | sed "s/STANDBY/\$2/g" | kubectl replace -f -
fi

if [ "\$2" == "UNJOIN" ]; then
  kubectl get openmcpcluster $1 -n openmcp -o yaml | sed "s/JOIN/\$2/g" | kubectl replace -f -
fi

if [ "\$2" == "STANDBY" ]; then
  kubectl get openmcpcluster $1 -n openmcp -o yaml | sed "s/UNJOIN/\$2/g" | kubectl replace -f -
fi

EOF

chmod +x kubectl-join_status

mv kubectl-join_status /usr/local/bin

echo "--Install kubectl-join_status plugin--"
