#!/bin/bash

OPENMCP_API_SERVER="openmcp-apiserver.openmcp.default-domain.svc.openmcp.example.org"
PORT="8080"
KUBECONFIG=`echo $KUBECONFIG`

echo "-----------------------------------------------------------"
echo "You Must Set '~/.hosts' File Before Request Join To OpenMCP"
echo "-----------------------------------------------------------"

if [ "$KUBECONFIG" == "" ]; then
  echo "Set KUBECONFIG Variable [~/.kube/config]"
  KUBECONFIG=~/.kube/config
fi

#if [ "$1" == "" ]; then
#  echo "Please Set OpenMCP IP:PORT"
#  echo "ex) kubectl request-join 0.0.0.0:0"
#  exit 1
#fi

echo ">>> Request OpenMCP to join cluster"

#echo -n | openssl s_client -connect $1 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > server.crt
echo -n | openssl s_client -connect $OPENMCP_API_SERVER:$PORT | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > server.crt
curl https://$OPENMCP_API_SERVER:$PORT/join -F file=@"$KUBECONFIG" --cacert server.crt
rm server.crt
