#!/bin/bash

if [ "$1" == "" ]; then
  echo "Please Input cluster name and platform if you need"
  echo "ex) kubectl join cluster1 (PLATFORM)"
  exit 1
elif [[ "$2" == "GKE" ]] || [[ "$2" == "EKS" ]] || [[ "$2" == "AKS" ]]; then
  kubectl patch openmcpcluster $1 -n openmcp --type='json' -p '[{"op":"replace","path":"/spec/joinStatus","value":"JOINING"}]'
else
  read -p "Input MetalLB IP Address Range (FROM) : " address_from
  read -p "Input MetalLB IP Address Range (TO) : " address_to

  kubectl patch openmcpcluster $1 -n openmcp --type='json' -p '[{"op":"replace","path":"/spec/metalLBRange/addressFrom","value": '$address_from'}]'
  sleep 2
  kubectl patch openmcpcluster $1 -n openmcp --type='json' -p '[{"op":"replace","path":"/spec/metalLBRange/addressTo","value": '$address_to'}]'
  sleep 2
  kubectl patch openmcpcluster $1 -n openmcp --type='json' -p '[{"op":"replace","path":"/spec/joinStatus","value":"JOINING"}]'
fi
