#!/bin/bash

if [ "$1" == "" ]; then
  echo "Please Input Cluster Name"
  echo "ex) kubectl join cluster1"
  exit 1
else
  read -p "Input MetalLB IP Address Range (FROM) : " address_from
  read -p "Input MetalLB IP Address Range (TO) : " address_to

  kubectl patch openmcpcluster $1 -n openmcp --type='json' -p '[{"op":"replace","path":"/spec/joinStatus","value":"JOIN"}]'
  kubectl patch openmcpcluster $1 -n openmcp --type='json' -p '[{"op":"replace","path":"/spec/metalLBRange/addressFrom","value": '$address_from'}]'
  kubectl patch openmcpcluster $1 -n openmcp --type='json' -p '[{"op":"replace","path":"/spec/metalLBRange/addressTo","value": '$address_to'}]'

  #kubectl get openmcpcluster $1 -n openmcp -o yaml | sed "s/IP_ADDRESS_FROM/$address_from/g" | kubectl replace -f -
  #kubectl get openmcpcluster $1 -n openmcp -o yaml | sed "s/IP_ADDRESS_TO/$address_to/g" | kubectl replace -f -
  #kubectl get openmcpcluster $1 -n openmcp -o yaml | sed "s/UNJOIN/JOIN/g" | kubectl replace -f -
fi
