#!/bin/bash

OPENMCP_API_SERVER="openmcp-apiserver.openmcp.default-domain.svc.openmcp.example.org"
PORT="8080"

if [[ "$1" == "GKE" ]] || [[ "$1" == "EKS" ]] || [[ "$1" == "AKS" ]]; then
  echo "Cloud Cluster [$1]"
else
  echo "Error : Input Cloud Cluster Type"
  echo "ex) kubectl regist-join GKE gke-cluster"
  exit 1
fi

if [ "$2" = "" ]; then
  echo "Error : Input Cluster Name"
  echo "ex) kubectl regist-join GKE gke-cluster"
  exit 1
fi

touch kubeconfig
export KUBECONFIG=./kubeconfig

if [ "$1" == "GKE" ]; then
  gcloud container clusters get-credentials $2
  kubectl get pods &>-
  rm -
elif [ "$1" == "EKS" ]; then
  aws eks update-kubeconfig --name $2
elif [ "$1" == "AKS" ]; then
  az aks get-credentials --resource-group openmcp --name $2 --file ./kubeconfig
fi

export KUBECONFIG=~/.kube/config
echo -n | openssl s_client -connect $OPENMCP_API_SERVER:$PORT | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > server.crt
curl -F file=@"kubeconfig" "https://$OPENMCP_API_SERVER:$PORT/joinCloud?clustername=$2&clustertype=$1" --cacert server.crt
rm server.crt
rm kubeconfig

