// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"openmcp/openmcp/apis/policy/v1alpha1.OpenMCPPolicy":       schema_pkg_apis_policy_v1alpha1_OpenMCPPolicy(ref),
		"openmcp/openmcp/apis/policy/v1alpha1.OpenMCPPolicySpec":   schema_pkg_apis_policy_v1alpha1_OpenMCPPolicySpec(ref),
		"openmcp/openmcp/apis/policy/v1alpha1.OpenMCPPolicyStatus": schema_pkg_apis_policy_v1alpha1_OpenMCPPolicyStatus(ref),
	}
}

func schema_pkg_apis_policy_v1alpha1_OpenMCPPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OpenMCPPolicy is the Schema for the openmcpPolicys API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST policy this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git/community/contributors/devel/api-conventions.md#policys",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("openmcp/openmcp/apis/policy/v1alpha1.OpenMCPPolicySpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("openmcp/openmcp/apis/policy/v1alpha1.OpenMCPPolicyStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta", "openmcp/openmcp/apis/policy/v1alpha1.OpenMCPPolicySpec", "openmcp/openmcp/apis/policy/v1alpha1.OpenMCPPolicyStatus"},
	}
}

func schema_pkg_apis_policy_v1alpha1_OpenMCPPolicySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OpenMCPPolicySpec defines the desired state of OpenMCPPolicy",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_policy_v1alpha1_OpenMCPPolicyStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OpenMCPPolicyStatus defines the observed state of OpenMCPPolicy",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
