apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeploy
  namespace: openmcp2
spec:
  replicas: 30
  labels:
      app: openmcp-nginx
      test: "yes"
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
<<<<<<< HEAD
            - image: nginx
              name: nginx
              resources:
                requests:
                  memory: "10"
                  cpu: "0.1"
=======
          - image: nginx
            name: nginx
#            resources:
#              requests:
#                memory: "100"
#                cpu: "0.1"
>>>>>>> 55ddc79c0f9409efd12d0a54c7c29db10d458769
