apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: hpa-minmax-distribution-mode
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: OpenMCPHybridAutoScaler
      policies:
        - type: Mode
          value:
            - Unequal
  rangeOfApplication: All
  policyStatus: Enabled
